services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: survey-mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD:-SurveyPass123!}"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/lib/mssql

volumes:
  mssql-data:
